version: '3'

services:
  postgresql-master:
    image: 'bitnami/postgresql:9.6'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=tripify
      - POSTGRES_INITDB_ARGS="--encoding=utf8"
  postgresql-slave:
    image: 'bitnami/postgresql:9.6'
    ports:
      - 5433:5432
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRES_INITDB_ARGS="--encoding=utf8"
